# Generated by Django 4.0.2 on 2022-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('anons', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('full_text', models.TextField(max_length=5000, verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
